import time
def ambient_load():
    raw_input("Press continue...")
    print("connect ambient load to receiver input \n")
    raw_input("Press Enter to continue...")
    print("make sure that high pass filter connected to the ports of ambient load \n")
    raw_input("Press Enter to continue...")
    print("make sure that voltage supply connected to the ambient load is set to zero \n")
    raw_input("Press Enter to continue...")
    print("make sure that termistor port is connected to labjack \n")

    raw_input("Press Enter to continue...")
    print("Start the spectrum observing program and temperature monitoring program \n")
    raw_input("Press Enter to continue...")
    print("Wait for 24 hr while taking spectrum and temerature \n")
    time.sleep(5)
    print("Completed the ambient spetrum measurment \n")
    print("Stop the spectrum observing program and temperature monitotring program \n")
    raw_input("Press Enter to continue...")
    print("Take S11 measurments \n")
    print("Set the switching voltage to 37 V and measure S11 and save as External01 \n")
    raw_input("Press Enter to continue...")
    print("Set the switching voltage to 37 V and measure S11 and save as External02 \n")
    raw_input("Press Enter to continue...")
    print("Set the switching voltage to 34 V andm easure S11 and save as Match01 \n")
    raw_input("Press Enter to continue...")
    print("Set the switching voltage to 34 V and measure S11 and save as Match02 \n")
    raw_input("Press Enter to continue...")
    print("Set the switching voltage to 31.3 V and measure S11 and save as Short01 \n")
    raw_input("Press Enter to continue...")
    print("Set the switching voltage to 31.3 V and measure S11 and save as Short02 \n")
    raw_input("Press Enter to continue...")
    print("Set the switching voltage to 28 V and measure S11 and save as Open01 \n")
    raw_input("Press Enter to continue...")
    print("Set the switching voltage to 28 V and measure S11 and save as Open02 \n")
    raw_input("Press Enter to continue...")
def hotload():
    print("Set 12V to turn on the hotload \n")
    raw_input("Press Enter to continue...")
    print("Start the spectrum observing program and temperature monitoring program \n")
    raw_input("Press Enter to continue...")
    print("Wait for 24 hr while taking spectrum and temerature \n")
    time.sleep(5)
    print("Completed the hotload spetrum measurment \n")
    raw_input("Press Enter to continue...")
    print("Stop the spectrum observing program and temperature monitotring program \n")
    print("Take S11 measurments for hot load \n")
    print("Set the switching voltage to 37 V and measure S11 and save as External01 \n")
    raw_input("Press Enter to continue...")
    print("Set the switching voltage to 37 V and measure S11 and save as External02 \n")
    raw_input("Press Enter to continue...")
    print("Set the switching voltage to 34 V and measure S11 and save as Match01 \n")
    raw_input("Press Enter to continue...")
    print("Set the switching voltage to 34 V and measure S11 and save as Match02 \n")
    raw_input("Press Enter to continue...")
    print("Set the switching voltage to 31.3 V and measure S11 and save as Short01 \n")
    raw_input("Press Enter to continue...")
    #print("Set the switching voltage to 31.3 V and measure S11 and save as Short02 \n")
    #raw_input("Press Enter to continue...")
    print("Set the switching voltage to 28 V and measure S11 and save as Open01 \n")
    raw_input("Press Enter to continue...")
    print("Set the switching voltage to 28 V and measure S11 and save as Open02 \n")
    raw_input("Press Enter to continue...")
    print("Set 0V to turn of the hotload \n")
    raw_input("Press Enter to continue...")

def main():
    ambient()
if __name__=='__main__':
    main()
    main()
