#!/bin/bash
import time
import subprocess
from Temp_sensor_with_time_U6 import temp_sensor
#import PX14400
import shutil
import sys
from S11_VNA import S11
#from termcolor import colored
#sys.stdout.write("\033[1;31m")
def ambient_load(temp,time_1):
    print("****************************************")
    print("****************************************")
    print("Starting Ambient load calibration")
    print("****************************************")
    print("****************************************")

    print('temp=',temp)
    raw_input ('Press Enter to continue...')
    print("\n")
    print("connect ambient load to receiver input \n")
    print("\n")
    raw_input("Press Enter to continue...")
    print("\n")
    print("make sure that high pass filter connected to the ports of ambient load \n")
    print("\n")
    raw_input("Press Enter to continue...")
    print("\n")
    print("make sure that voltage supply connected to the ambient load is set to zero \n")
    print("\n")
    raw_input("Press Enter to continue...")
    print("\n")
    print("make sure that thermistor port is connected to labjack \n")
    print("\n")
    raw_input("Press Enter to continue...")
    print("--------------------------------------------------------------------------")
    print("--------------------------------------------------------------------------")
    print("Starting the spectrum observing program and temperature monitoring program \n")
    print("--------------------------------------------------------------------------")
    print("--------------------------------------------------------------------------")
    raw_input("Press Enter to continue...")
    #print("Wait for 24 hr while taking spectrum and temerature \n")
    
    
    subprocess.Popen(["/home/edges-0/Desktop/code/Edges2/fastspec-1.1.0/fastspec_single", "-i", "/home/edges-0/Desktop/code/Edges2/fastspec-1.1.0/edges.ini", "-p", "-s",str(time_1)])
    
    #subprocess.Popen(['python','/home/edges-0/Desktop/Titu/Automation/Temp_sensor_with_time.py', time, temp])
    temp_sensor() 
    time.sleep(34)
    #print("Completed the ambient spetrum measurment \n")
    print("--------------------------------------------------------------------------")
    print("--------------------------------------------------------------------------")
    print("                      finished the spectrum measurement \n")
    print("--------------------------------------------------------------------------")
    print("--------------------------------------------------------------------------")
    raw_input("Press Enter to continue...")
    print("\n")
    print("Take S11 measurements \n")
    print("\n")
    print("Set the switching voltage to 37 V and measure S11, save as External01 \n")
    
    print("\n")
    raw_input("Press Enter to continue...")
    print("--------------------------------------------------------------------------")
    print("--------------------------------------------------------------------------")
    print("                  Starting S11 External01 measurment\n")
    print("--------------------------------------------------------------------------")
    print("--------------------------------------------------------------------------")
    S11()
    shutil.move('S11.csv','External01.csv')
    print("Set the switching voltage to 37 V and measure S11,save as External02 \n")
    print("\n")
    raw_input("Press Enter to continue...")
    print("--------------------------------------------------------------------------")
    print("--------------------------------------------------------------------------")
    print("                  Starting S11 External02 measurment\n")
    print("--------------------------------------------------------------------------")
    print("--------------------------------------------------------------------------")
    S11()
    shutil.move('S11.csv','External02.csv')
    print("Set the switching voltage to 34 V and measure S11, save as Match01 \n")
    print("\n")
    raw_input("Press Enter to continue...")
    print("--------------------------------------------------------------------------")
    print("--------------------------------------------------------------------------")
    print("                  Starting S11 Match01 measurment\n")
    print("--------------------------------------------------------------------------")
    print("--------------------------------------------------------------------------")
    
    S11()
    shutil.move('S11.csv','Match01.csv')
    print("Set the switching voltage to 34 V and measure S11, save as Match02 \n")
    print("\n")
    raw_input("Press Enter to continue...")
    print("--------------------------------------------------------------------------")
    print("--------------------------------------------------------------------------")
    print("                  Starting S11 Match02 measurment\n")
    print("--------------------------------------------------------------------------")
    print("--------------------------------------------------------------------------")
    #print("Taking S11 Match02 measurment\n")
    S11()
    shutil.move('S11.csv','Match02.csv')
    print("Set the switching voltage to 31.3 V and measure S11, save as Short01 \n")
    print("\n")
    raw_input("Press Enter to continue...")
    print("--------------------------------------------------------------------------")
    print("--------------------------------------------------------------------------")
    print("                  Starting S11 Short01 measurment\n")
    print("--------------------------------------------------------------------------")
    print("--------------------------------------------------------------------------")
    #print("Taking S11 Short01 measurment\n")
    S11()
    shutil.move('S11.csv','Short01.csv')
    print("Set the switching voltage to 31.3 V and measure S11, save as Short02 \n")
    print("\n")
    raw_input("Press Enter to continue...")
    print("--------------------------------------------------------------------------")
    print("--------------------------------------------------------------------------")
    print("                  Starting S11 Short02 measurment\n")
    print("--------------------------------------------------------------------------")
    print("--------------------------------------------------------------------------")
    #print("Taking S11 Short02 measurment\n")
    S11()
    shutil.move('S11.csv','Short02.csv')
    print("Set the switching voltage to 28 V and measure S11 and save as Open01 \n")
    print("\n")
    raw_input("Press Enter to continue...")
    print("--------------------------------------------------------------------------")
    print("--------------------------------------------------------------------------")
    print("                  Starting S11 Open01 measurment\n")
    print("--------------------------------------------------------------------------")
    print("--------------------------------------------------------------------------")
    #print("Taking S11 Open01 measurment\n")
    S11()
    shutil.move('S11.csv','Open01.csv')
    print("Set the switching voltage to 28 V and measure S11, save as Open02 \n")
    print("\n")
    raw_input("Press Enter to continue...")
    print("--------------------------------------------------------------------------")
    print("--------------------------------------------------------------------------")
    print("                  Starting S11 Open02 measurment\n")
    print("--------------------------------------------------------------------------")
    print("--------------------------------------------------------------------------")
    #print("Taking S11 Open02 measurment\n")
    S11()
    shutil.move('S11.csv','Open02.csv')

def main():
    ambient()
if __name__=='__main__':
    main()
    #main()
